### PR TITLE
fix: handle error resolution

### LINKED ISSUE #12442: SwagMigrationMagento Error Resolution compatibility
### Technical TODO

check https://github.com/shopware/SwagMigrationMagento/pull/31 for compatibility with https://github.com/shopware/SwagMigrationAssistant/pull/41

### PR DESCRIPTION
**Pull request by jozsefdamokos**
fixes https://github.com/shopware/shopware/issues/12442

- remove validation from converters
- fix many errors
- add magento 2.4 profile

### CODE REVIEW

File: src/Profile/Magento/Converter/OrderConverter.php [hunk 1]
```diff
@@ -111,19 +95,11 @@ public function getSourceIdentifier(array $data): string
...
-        /*
-         * Checking required fields and logging missing ones
-         */
-        $fields = $this->checkForEmptyRequiredDataFields($data, self::$requiredDataFieldKeys);
-        if (!isset($data['orders']['entity_id'])) {
-            $fields[] = 'entity_id';
-        }
-
-        if (!empty($fields)) {
+        if (!isset($data['orders']) || !isset($data['orders']['entity_id'])) {
```
Comment (MalteJanz) [inline src/Profile/Magento/Converter/OrderConverter.php]: nitpick, you could remove the first condition, `isset` already handles it if any of the array keys don't exists, so there is no need to check them one by one.

```suggestion
        if (!isset($data['orders']['entity_id'])) {
```

File: src/Profile/Magento/Converter/OrderConverter.php [hunk 2]
```diff
@@ -832,38 +783,47 @@ protected function convertOrderCustomer(array &$converted, array &$data): bool
...
+            if (!empty($shippingAddress)) {
                 $converted['orderCustomer']['customer']['addresses'][] = $shippingAddress;
             }
 
-            $converted['orderCustomer']['customer']['defaultShippingAddressId'] = $shippingAddress['id'];
+            if (isset($shippingAddress['id'])) {
+                $converted['orderCustomer']['customer']['defaultShippingAddressId'] = $shippingAddress['id'];
+            }
+
+            if (empty($shippingAddress) && isset($billingAddress['id'])) {
```
Comment (MalteJanz) [inline src/Profile/Magento/Converter/OrderConverter.php:824]: nitpick: because the first condition is basically the inverse of the previous if, you could use an `elseif` here and make it a little easier to read:

```suggestion
            elseif (isset($billingAddress['id'])) {
```

File: src/Profile/Magento/Gateway/Local/Reader/AbstractReader.php [hunk 3]
```diff
@@ -91,13 +91,17 @@ protected function addTableSelection(QueryBuilder $query, string $table, string
...
-                [$tableAlias, $column->getObjectName()->toString()],
-                '`#tableAlias#`.`#column#` AS `#tableAlias#.#column#`'
-            );
+            $columnName = $column->getObjectName()->toString();
 
-            $query->addSelect($selection);
+            $columnName = trim($columnName, '"`');
+
+            $query->addSelect(\sprintf(
+                '%s.%s AS `%s.%s`',
```
Comment (MalteJanz) [inline src/Profile/Magento/Gateway/Local/Reader/AbstractReader.php]: Just wondering if this would also still work, to have the table and field name quoted, which I think is a good practice here to make sure also strange table / field names are properly escaped.


```suggestion
                '`%s`.`%s` AS `%s.%s`',
```

File: src/Profile/Magento24/Gateway/Local/Reader/Magento24CountryReader.php [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+use SwagMigrationAssistant\Migration\DataSelection\DefaultEntities;
+use SwagMigrationAssistant\Migration\MigrationContextInterface;
+
+#[Package('fundamentals@after-sales')]
+class Magento24CountryReader extends Magento2CountryReader
+{
+    public function supports(MigrationContextInterface $migrationContext): bool
+    {
+        return $migrationContext->getProfile() instanceof Magento24Profile
+            && $migrationContext->getGateway()->getName() === Magento19LocalGateway::GATEWAY_NAME
```
Comment (MalteJanz) [inline src/Profile/Magento24/Gateway/Local/Reader/Magento24CountryReader.php]: Shouldn't this be 24?

```suggestion
            && $migrationContext->getGateway()->getName() === Magento24LocalGateway::GATEWAY_NAME
```

File: src/Profile/Magento24/Premapping/Magento24CustomerGroupReader.php [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+use Swag\MigrationMagento\Profile\Magento\Premapping\CustomerGroupReader;
+use Swag\MigrationMagento\Profile\Magento24\Magento24Profile;
+use SwagMigrationAssistant\Migration\MigrationContextInterface;
+
+#[Package('fundamentals@after-sales')]
+class Magento24CustomerGroupReader extends CustomerGroupReader
+{
+    public function supports(MigrationContextInterface $migrationContext, array $entityGroupNames): bool
+    {
+        return $migrationContext->getProfile() instanceof Magento24Profile;
```
Comment (MalteJanz) [inline src/Profile/Magento24/Premapping/Magento24CustomerGroupReader.php]: Shouldn't this have another condition to only be active when the customer data set was selected (e.g. like you are doing in `src/Profile/Magento24/Premapping/Magento24AdminStoreReader.php`)?

File: src/SwagMigrationMagento.php [hunk 6]
```diff
@@ -25,11 +25,12 @@ public function build(ContainerBuilder $container): void
 
         $loader = new XmlFileLoader($container, new FileLocator(__DIR__ . '/DependencyInjection/'));
         $loader->load('magento.xml');
-        $loader->load('magento19.xml');
+        // $loader->load('magento19.xml');
```
Comment (MalteJanz) [inline src/SwagMigrationMagento.php:28]: Do we already have a decision here to drop support for it? Either way I would suggest adding an issue for this and mentioning it in a comment here.

Because I think it would be better to deprecate / delete that profile in another, follow up PR, this one is already huge 😅

File: src/SwagMigrationMagento.php [hunk 7]
```diff
@@ -25,11 +25,12 @@ public function build(ContainerBuilder $container): void
...
         $loader->load('magento20.xml');
         $loader->load('magento21.xml');
         $loader->load('magento22.xml');
         $loader->load('magento23.xml');
+        $loader->load('magento24.xml');
```
Comment (MalteJanz) [inline src/SwagMigrationMagento.php:33]: Nice that you went ahead and added support for 2.4 💪

File: CHANGELOG_de-DE.md [hunk 8]
```diff
@@ -1,3 +1,8 @@
+# 11.0.0
+- Compatibility with SwagMigrationAssistant version 16 and added error resolution support.
+- Removed support for Magento 1.9
+- Added new profile for Magento 2.4
```
Comment (MalteJanz) [inline CHANGELOG_de-DE.md]:
```suggestion
- Kompatibilität mit Migration-Assistant Version 16 hinzugefügt und Unterstützung für die Fehlerbehebung eingebaut.
- Unterstützung für Magento 1.9 entfernt
- Neues Profil für Magento 2.4 hinzugefügt
```

**Review by MalteJanz — APPROVED** [review]

File: src/Profile/Magento/Converter/OrderConverter.php (hunk 2 above)
Comment (jozsefdamokos) [reply src/Profile/Magento/Converter/OrderConverter.php:824]: I would not be exactly the same

File: src/SwagMigrationMagento.php (hunk 6 above)
Comment (jozsefdamokos) [reply src/SwagMigrationMagento.php:28]: I would have to fix the tests for 1.9, thats why I did it here

Comment (MalteJanz) [reply src/SwagMigrationMagento.php:28]: Yes got that, but for fully removing it and the dead code, there is still more work to do right? Just wanted to make sure we follow up on this and don't leave the dead + unmaintained implementation in there 🤔

Comment (jozsefdamokos) [reply src/SwagMigrationMagento.php:28]: Yes, we can do that in a separate PR, issue: https://github.com/shopware/shopware/issues/15331

File: tests/Profile/Magento2/Converter/Magento2CategoryConverterTest.php [hunk 9]
```diff
@@ -474,68 +473,4 @@ public function testConvertWithParentButParentNotConverted23(): void
             static::assertSame(Response::HTTP_NOT_FOUND, $e->getStatusCode());
         }
     }
-
-    public function testConvertWithoutLocale20(): void
```
Comment (larskemper) [inline tests/Profile/Magento2/Converter/Magento2CategoryConverterTest.php:478]: don't know if I would delete them: change the expected value to "no logs", so we test this behavior

**Review by larskemper — APPROVED** [review]

**Review by vintagesucks — APPROVED** [review]

File: tests/Profile/Magento2/Converter/Magento2CategoryConverterTest.php (hunk 9 above)
Comment (jozsefdamokos) [reply tests/Profile/Magento2/Converter/Magento2CategoryConverterTest.php:478]: Not done due to time constraint
